print( 'Hello, Python : 안녕 파이썬 !' )
print( 'Hello, Python : 안녕 파이썬 !!' )
print( 'Hello, Python : 안녕 파이썬 !!!' )
print( 'Hello, Python : 안녕 파이썬 !!!!' )
print( 'Hello, Python : 안녕 파이썬 !!!!!' )
print( 'Hello, Python : 안녕 파이썬 !!!!!!' )
print( 'Hello, Python : 안녕 파이썬 !!!!!!!' )